# This code takes the .npz file generated by the SfM, so the 3d map of the object and converts it into
# - .mrk.json
# - .fcsv
# use from CLI: python map_for_slicer.py marker_map_aligned.npz
# options: --coord-system LPS|RAS   (default: RAS)
# RAS is Right-Anterior-Superior
# LPS is Left-Posterior-Superior
# Slicer uses RAS internally and converts it if you upload data in LPS.


import argparse
import json
from pathlib import Path
import numpy as np

def load_npz_marker(npz_path: Path):
    npz = np.load(npz_path, allow_pickle=True)
    required_keys = ["marker_ids", "marker_points"]
    for k in required_keys:
        if k not in npz:
            raise KeyError(f"Chiave '{k}' mancante nel file npz.")

    marker_ids = npz["marker_ids"]
    marker_points = npz["marker_points"]

    if marker_points.shape[0] != marker_ids.shape[0]:
        raise ValueError(
            f"marker_ids ({marker_ids.shape[0]}) e marker_points "
            f"({marker_points.shape[0]}) hanno lunghezze diverse."
        )

    return marker_ids, marker_points


def write_mrk_json(output_path: Path, marker_ids, marker_points, coord_system: str = "RAS"):
    coord_system = coord_system.upper()
    if coord_system not in ("LPS", "RAS"):
        raise ValueError("coord_system deve essere 'LPS' oppure 'RAS'.")

    control_points = []
    for pid, p in zip(marker_ids, marker_points):
        control_points.append(
            {
                "label": str(pid),
                "position": [float(p[0]), float(p[1]), float(p[2])],
            }
        )

    data = {
        "@schema": "https://raw.githubusercontent.com/Slicer/Slicer/main/Modules/Loadable/Markups/Resources/Schema/markups-schema-v1.0.0.json#",
        "markups": [
            {
                "type": "Fiducial",
                "coordinateSystem": coord_system,
                "controlPoints": control_points,
            }
        ],
    }

    with output_path.open("w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)


def write_fcsv(output_path: Path, marker_ids, marker_points, coord_system: str = "RAS"):
    coord_system = coord_system.upper()
    if coord_system not in ("LPS", "RAS"):
        raise ValueError("coord_system deve essere 'LPS' oppure 'RAS'.")

    with output_path.open("w", encoding="utf-8", newline="\n") as f:
        # Header
        f.write("# Markups fiducial file version = 4.13\n")
        f.write(f"# CoordinateSystem = {coord_system}\n")
        f.write("# columns = id,x,y,z,ow,ox,oy,oz,vis,sel,lock,label,desc,associatedNodeID\n")

        for idx, (pid, p) in enumerate(zip(marker_ids, marker_points)):
            x, y, z = map(float, p)
            row = [
                str(idx),           # id (row index)
                f"{x:.8f}",
                f"{y:.8f}",
                f"{z:.8f}",
                "0", "0", "0", "1",  # ow, ox, oy, oz (quaternion identity)
                "1", "1", "0",       # vis, sel, lock
                str(pid),            # label -> uso marker_id come etichetta
                "",                  # desc
                "",                  # associatedNodeID
            ]
            f.write(",".join(row) + "\n")


def write_itk_identity_tfm(output_path: Path):
    """
    ITK linear transform 3D identity (.tfm).
    Identity for marker frame.
    """
    lines = [
        "#Insight Transform File V1.0",
        "# Transform 0",
        "Transform: AffineTransform_double_3_3",
        "Parameters: 1 0 0 0 1 0 0 0 1 0 0 0",
        "FixedParameters: 0 0 0",
        "",
    ]
    with output_path.open("w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))


def main():
    parser = argparse.ArgumentParser(
        description="Converti marker_map_aligned.npz in Markups + Transform per 3D Slicer.")
    parser.add_argument("npz_path", type=str, help="Percorso al file .npz (marker_map_aligned.npz).")
    parser.add_argument(
        "--coord-system",
        type=str,
        default="RAS",
        help="Sistema di coordinate da dichiarare nei file (LPS o RAS). Default: RAS.",
    )

    args = parser.parse_args()
    npz_path = Path(args.npz_path)
    coord_system = args.coord_system

    if not npz_path.exists():
        raise FileNotFoundError(f"File non trovato: {npz_path}")

    print(f"Carico NPZ: {npz_path}")
    marker_ids, marker_points = load_npz_marker(npz_path)
    print(f"Trovati {marker_points.shape[0]} punti 3D.")

    base = npz_path.with_suffix("")  # remove .npz
    mrk_json_path = base.with_name(base.name + "_marker_points.mrk.json")
    fcsv_path = base.with_name(base.name + "_marker_points.fcsv")
    tfm_path = base.with_name(base.name + "_marker_frame_identity.tfm")

    print(f"Scrivo mrk.json → {mrk_json_path}")
    write_mrk_json(mrk_json_path, marker_ids, marker_points, coord_system)

    print(f"Scrivo fcsv → {fcsv_path}")
    write_fcsv(fcsv_path, marker_ids, marker_points, coord_system)

    print(f"Scrivo ITK transform identity (.tfm) → {tfm_path}")
    write_itk_identity_tfm(tfm_path)

    print("Fatto.")
    print(
        "File generati:\n"
        f"- {mrk_json_path.name}  (Markups JSON, punti del marker)\n"
        f"- {fcsv_path.name}      (Markups FCSV, punti del marker)\n"
        f"- {tfm_path.name}       (Transform identità per il frame del marker)\n"
    )
    print(
        "In 3D Slicer puoi caricare il .mrk.json / .fcsv come Markups\n"
        "e il .tfm come LinearTransform (es. rinominalo in 'MarkerToTracker' o simile)."
    )

if __name__ == "__main__":
    main()
