# This code is used to run marker-based tracking using a pre-built map and recorded detections.
# It loads the necessary data, initializes the tracker, and processes the detections to estimate poses.

from __future__ import annotations

from pathlib import Path

from track_from_map import (MapTracker, load_camera_intrinsics, load_detection_records, load_map, load_npz_image_lookup, run_tracking_from_records)


def main() -> None:
    # load here the path for your 3d map, after structure from motion
    map_path = Path(
        r"C:\Users\samue\Desktop\GIT_STL\US_Trackers\Sam_HydraMarkers\6x10_3x3tag_1x10tag_6x2tag/mapping/sfm_outputs/marker_map_aligned.npz"
    )
    # load here the paths for your camera calibration matrices
    camera_matrix_path = Path(
        r"C:\Users\samue\Desktop\GIT_STL\US_Trackers\calib_data\basler_dart\camera_mtx.npy"
    )
    distortion_path = Path(
        r"C:\Users\samue\Desktop\GIT_STL\US_Trackers\calib_data\basler_dart\camera_dist.npy"
    )
    # root folder containing trial_* sub-directories generated by ReadMarker_FromNPZ
    trials_root = Path(
        r"C:\Users\samue\Desktop\GIT_STL\US_Trackers\Sam_HydraMarkers\6x10_3x3tag_1x10tag_6x2tag\accuracy_trans_increment_z"
    )

    # remember to set Ransac distance maximum and temporal check thresholds

    display = False
    axis_length = 50.0
    min_markers = 6
    report_every = 10
    quit_key = "q"
    use_pose_prior = True
    display_delay_ms = 1  # increase if you want to slow down playback

    for path, label in ((map_path, "map file"), (camera_matrix_path, "camera matrix"), (distortion_path, "distortion"), (trials_root, "trials root")):
        if not path.exists():
            raise FileNotFoundError(f"{label.capitalize()} not found: {path}")

    def _trial_index(path: Path) -> int:
        try:
            return int(path.name.split("_")[-1])
        except (ValueError, IndexError):
            return 10_000

    trial_dirs = sorted((p for p in trials_root.iterdir() if p.is_dir() and p.name.lower().startswith("trial_")), key=_trial_index)
    if not trial_dirs:
        raise FileNotFoundError(f"No trial_* directories found in {trials_root}")

    normalized_dirs: list[Path] = []
    for idx, original_dir in enumerate(trial_dirs, start=1):
        target_name = f"trial_{idx:02d}"
        target_dir = trials_root / target_name
        if original_dir == target_dir:
            normalized_dirs.append(original_dir)
            continue
        if target_dir.exists():
            raise FileExistsError(f"Cannot rename {original_dir} to {target_name}: target already exists")
        original_dir.rename(target_dir)
        normalized_dirs.append(target_dir)
        print(f"Renamed {original_dir.name} -> {target_name}")
    trial_dirs = normalized_dirs

    map_data = load_map(map_path)
    print(f"Loaded map with {map_data.marker_ids.size} markers and " f"{map_data.pose_ids.size} reference poses from {map_path}")

    camera_matrix, distortion = load_camera_intrinsics(camera_matrix_path, distortion_path)
    #print(f"Camera matrix:\n{camera_matrix}")

    for trial_dir in trial_dirs:
        detections_path = trial_dir / "detections_data.npz"
        if not detections_path.exists():
            print(f"Skipping {trial_dir}: missing {detections_path.name}")
            continue

        print(f"\n=== Running tracking for {trial_dir.name} ===")
        tracker = MapTracker(map_data, camera_matrix, distortion)
        detection_records = load_detection_records(detections_path)
        print(f"Loaded {len(detection_records)} detection records from {detections_path}")

        image_lookup = None
        if display:
            frames_npz_candidates = sorted(trial_dir.glob("tracking_rec_test*.npz"))
            if not frames_npz_candidates:
                raise FileNotFoundError(f"Display is enabled but no tracking_rec_test*.npz was found in {trial_dir}")
            frames_npz_path = frames_npz_candidates[0]
            image_lookup = load_npz_image_lookup(frames_npz_path, data_key="data", image_key="img")

        run_tracking_from_records(tracker, detection_records, image_lookup=image_lookup, display=display, axis_length=axis_length, min_markers=min_markers, report_every=max(1, report_every), quit_key=quit_key, use_pose_prior=use_pose_prior, display_delay_ms=display_delay_ms, plot_output_dir=trial_dir, results_output_path=trial_dir / "tracking_results.npy")

if __name__ == "__main__":
    main()
